### ISSUE TITLE
extend censo_escolar earlier

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/lodown#1]
@guilhermejacob  i'll do this later

**Comment by guilhermejacob** [comment]
Censo Escolar comes with a SAS input in 2006.
Consider adding a new method for this.

**Comment by ajdamico** [comment]
yep, it's just setting up an `if` block that diverts to `read_SAScii_monetdb`

**Comment by ajdamico** [comment]
i think i've fixed this with today's commits, but reopen if you disagree?  thanks
