### ISSUE TITLE
psid invalid multibyte string 2553 issue

### ISSUE THREAD

**Issue by jmcclosk1** [ajdamico/lodown#101]
Original command, output, error message and sessionInfo() output are all in the attached txt file (without my password).  

[psid_error_sessinfo.txt](https://github.com/ajdamico/lodown/files/1046087/psid_error_sessinfo.txt)

**Comment by ajdamico** [comment]
thank you for reporting this.  https://github.com/ajdamico/lodown/commit/5b98296c463bd184387efd0b6724b8c15d5c439e solves it
