### ISSUE TITLE
Error when installing archive package

### ISSUE THREAD

**Issue by petulla** [ajdamico/lodown#108]
Hey again. 

Trying to install your package.

Getting this error:

```r
* installing *source* package ‘archive’ ...
Package libarchive was not found in the pkg-config search path.
Perhaps you should add the directory containing `libarchive.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libarchive' found
Package libarchive was not found in the pkg-config search path.
Perhaps you should add the directory containing `libarchive.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libarchive' found
PKG_CFLAGS=
PKG_LIBS=
<stdin>:1:10: fatal error: 'archive.h' file not found
#include <archive.h>
         ^
1 error generated.
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libarchive was not found. Try installing:
 * deb: libarchive-dev (Debian, Ubuntu, etc)
 * rpm: libarchive-devel (Fedora, CentOS, RHEL)
 * csw: libarchive_dev (Solaris)
 * brew: libarchive (Mac OSX)
If libarchive is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libarchive.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘archive’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/archive’
Installation failed: Command failed (1)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL  \
  '/private/var/folders/w4/1dyx0ypn2ks3v2xk_bv7hpnh0000gp/T/Rtmp7Fxcwj/devtools9a0f2bf6036c/ajdamico-lodown-8c80ecb'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

ERROR: dependency ‘archive’ is not available for package ‘lodown’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/lodown’
Installation failed: Command failed (1)
```

I'm using your recommend code install commands:

```r
install.packages( "devtools" , repos = "http://cran.rstudio.com/" )
library(devtools)
install_github( "ajdamico/lodown" , dependencies = TRUE )
```

**Comment by ajdamico** [comment]
hi, if this thread doesn't solve the problem for you, i think you'll need to request help there..  https://github.com/jimhester/archive/issues/9  thanks

**Comment by rogeriocb2** [comment]
> install.packages( "devtools" , repos = "http://cran.rstudio.com/" )
Error in install.packages : Updating loaded packages

Restarting R session...

Error in gzfile(file, "wb") : cannot open the connection
Error saving session (options): R code execution error
WARNING: Forcing suspend of process in spite of all session data not being fully saved.
> install.packages("devtools", repos = "http://cran.rstudio.com/")
Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES.rds': HTTP status was '404 Not Found'
Installing package into ‘C:/Users/Rogério Sá/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.4/devtools_1.13.4.zip'
Content type 'application/zip' length 444002 bytes (433 KB)
downloaded 433 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Rogério Sá\AppData\Local\Temp\RtmpwlX2OQ\downloaded_packages
> install.packages("C:/Users/Rogério Sá/AppData/Local/Temp/RtmpwlX2OQ/downloaded_packages/devtools_1.13.4.zip", repos = NULL, type = "win.binary")
Installing package into ‘C:/Users/Rogério Sá/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
package ‘devtools’ successfully unpacked and MD5 sums checked
> library(devtools)
Warning message:
package ‘devtools’ was built under R version 3.4.2 
> install_github( "ajdamico/lodown" , dependencies = TRUE )
Downloading GitHub repo ajdamico/lodown@master
from URL https://api.github.com/repos/ajdamico/lodown/zipball/master
Installing lodown
Downloading GitHub repo jimhester/archive@master
from URL https://api.github.com/repos/jimhester/archive/zipball/master
Installing archive
Downloading GitHub repo tidyverse/glue@master
from URL https://api.github.com/repos/tidyverse/glue/zipball/master
Installing glue
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL "C:/Users/Rogério  \
  Sá/AppData/Local/Temp/RtmpwlX2OQ/devtools17d43a641f69/tidyverse-glue-58213a3"  \
  --library="C:/Users/Rogério Sá/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'glue' ...
Warning in file(file, if (append) "a" else "w") :
  cannot open file 'C:/Users/Rogirio Sa/Documents/R/win-library/3.4/glue/DESCRIPTION': No such file or directory
Error in file(file, if (append) "a" else "w") : 
  nÃ£o Ã© possÃ­vel abrir a conexÃ£o
ERROR: installing package DESCRIPTION failed for package 'glue'
* removing 'C:/Users/Rogério Sá/Documents/R/win-library/3.4/glue'
* restoring previous 'C:/Users/Rogério Sá/Documents/R/win-library/3.4/glue'
Installation failed: Command failed (1)
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL "C:/Users/Rogério  \
  Sá/AppData/Local/Temp/RtmpwlX2OQ/devtools17d4533d431c/jimhester-archive-079351e"  \
  --library="C:/Users/Rogério Sá/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'archive' ...
Warning in file(file, if (append) "a" else "w") :
  cannot open file 'C:/Users/Rogirio Sa/Documents/R/win-library/3.4/archive/DESCRIPTION': No such file or directory
Error in file(file, if (append) "a" else "w") : 
  nÃ£o Ã© possÃ­vel abrir a conexÃ£o
ERROR: installing package DESCRIPTION failed for package 'archive'
* removing 'C:/Users/Rogério Sá/Documents/R/win-library/3.4/archive'
Installation failed: Command failed (1)
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL "C:/Users/Rogério  \
  Sá/AppData/Local/Temp/RtmpwlX2OQ/devtools17d457d31f22/ajdamico-lodown-188d232"  \
  --library="C:/Users/Rogério Sá/Documents/R/win-library/3.4" --install-tests 

ERROR: dependency 'archive' is not available for package 'lodown'
* removing 'C:/Users/Rogério Sá/Documents/R/win-library/3.4/lodown'
Installation failed: Command failed (1)
