### ISSUE TITLE
possible data problem nychvs, longitudinal IDs

### ISSUE THREAD

**Issue by hjacobcarlson** [ajdamico/lodown#118]
Hi, I'm getting some other incorrect output, that I'm trying to figure out for the New York City Housing and Vacancy Survey.

The NYCHVS is longitudinal between census takings. I'm having trouble merging the files between years.

I'm able to match 2002 and 2005 just fine. But I don't get the right number of matches between 2005 and 2008 - I get about 2,800 when I should be getting about 13,000. 

Here's some code:

```
library(lodown)
library(dplyr)

file <- #set file save directory

nychvs_cat <-
  get_catalog( "nychvs" ,
               output_dir = file)

# years 2002-2008 only
nychvs_cat <- subset( nychvs_cat , year < 2011 )

# download the microdata to your local computer
lodown( "nychvs" , nychvs_cat )

# load in microdata
nychvs2002 <- readRDS(paste(file, "2002/occ.rds", sep = "/"))
nychvs2005 <- readRDS(paste(file, "2005/occ.rds", sep = "/"))
nychvs2008 <- readRDS(paste(file, "2008/occ.rds", sep = "/"))

# count matching cases between waves

nychvs2002 %>%
  semi_join(nychvs2005, by = "seqnum") %>%
  count()

nychvs2005 %>%
  semi_join(nychvs2008, by = "seqnum") %>%
  count()

```
Any ideas why? Thanks so much.

**Comment by ajdamico** [comment]
hi, could you find and fix the mistake with a pull request?  thanks

**Comment by hjacobcarlson** [comment]
Full disclosure, I'm a total amateur at this. I squinted at it really hard for a long time. I think I found an error, but not sure if it will fix the problem I had. From looking at the Furman SAS import scripts, they looked right for the seqnum variable. 

Sorry, I couldn't figure out how to test my script in the package. Thanks for your patience with me :)

**Comment by ajdamico** [comment]
let me know, thanks

**Comment by ajdamico** [comment]
sorry this broke travis and appveyor testing of the code on asdfree.com.  you'll need to test your code

**Comment by ajdamico** [comment]
hi, this broke again.  please confirm `lodown::lodown("nychvs",output_dir=tempdir())` runs properly on your fork of the project before submitting another pull request, thanks
