### ISSUE TITLE
Lodown datasus problem

### ISSUE THREAD

**Issue by marceloprudente** [ajdamico/lodown#123]
Hi,

Im trying to download datasus files with lodown, but the program gives me this error message:

"building catalog for datasus
Error in value[[3L]](cond) : 
  while creating directory C:\ftp:\ftp.datasus.gov.br\<a href="..">para o diretório de nível superior<
cannot create dir 'C:\ftp:\ftp.datasus.gov.br', reason 'Invalid argument'"

There is any solution? 
Thanks in advance

**Comment by guilhermejacob** [comment]
Can you provide the code and full output? Also, what OS are you using?

**Comment by marceloprudente** [comment]
I'm using Windows 10. This is the code and the full output:
`> lodown("datasus", output_dir = "C:/DATASUS/")
building catalog for datasus

Error in value[[3L]](cond) : 
  while creating directory C:\ftp:\ftp.datasus.gov.br\<a href="..">para o diretório de nível superior<
cannot create dir 'C:\ftp:\ftp.datasus.gov.br', reason 'Invalid argument'`

**Comment by ajdamico** [comment]
sorry the website datasus.gov.br is not accessible outside of brazil so i'm not supporting it.  thanks

**Comment by guilhermejacob** [comment]
@ajdamico , I guess you should drop https://github.com/ajdamico/lodown/blob/master/R/mtps.R for the same reason.

**Comment by rmaranhao** [comment]
Is there anything I can do to help?
Brazilian data is very hard to come by in friendly formats and your package
has been a huge help.


Um grande abraço,
Roberto.

-- 
Roberto Maranhão - Maranhão Consultoria
r.maranhao@gmail.com
(5531) 8482 4456

2017-11-21 20:01 GMT-02:00 Anthony Damico <notifications@github.com>:

**Comment by guilhermejacob** [comment]
I'd say try send Datasus people a message, requesting access for foreign connections. I tried a few months ago, but to no avail.
