### ISSUE TITLE
Error unzipping file with Ubuntu: "Invalid central directory signature"

### ISSUE THREAD

**Issue by jeffrosenblum** [ajdamico/lodown#128]
Hi Anthony, I might just be the most unlucky. I'm now having trouble with the ```archive``` package using Ubuntu (which use the unix ```libarchive```). No problem with the 2009 zip file, but no-go on the 2015 and 2014 5-year csv_pus.zip. I submitted an [issue](https://github.com/jimhester/archive/issues/13) to jimhester, but don't expect anything to come out of that.

Wondering if you would consider adding an option for manually extracting the downloads? 
```options( "lodown.unzip.auto" = FALSE )``` with a default of ```TRUE```?

Instead of calling the ```archive``` command ```archive::archive_extract( tf , dir = tempdir() )``` it could prompt the user to manually extract files and then hit ```enter``` to continue?

Thanks for considering.

**Comment by ajdamico** [comment]
sorry, i'd rather not do this.  i'll try to integrate the acs into perpetual testing soon, so issues like this disappear

https://github.com/ajdamico/asdfree/blob/master/README.md
