### ISSUE TITLE
Parsing errors in CPS basic for version January 1998 to December 2002

### ISSUE THREAD

**Issue by rubenhm** [ajdamico/lodown#132]
I'm getting all kinds of parsing failure notices and I think it's because of the dictionary file for that period.
The dictionary file should be http://thedataweb.rm.census.gov/pub/cps/basic/199801-/jan98dd.asc
The get_catalog_basic function only seems to look for *.txt files and misses the dictionary for that period, and instead is picking up the file https://thedataweb.rm.census.gov/pub/cps/basic/199801-/2000-2extract.txt, which does not seem to be the correct dictionary for that version.
The cps_dd_parser function may need special hardcoded fixes for that period. 

Any suggestions on how to fix this?

**Comment by ajdamico** [comment]
thanks for reporting this!  could you test out the latest version?  not sure if we'd also need to edit the lodown:::cps_dd_parser  function

**Comment by rubenhm** [comment]
Hi  Anthony
Thanks for looking into this. The get_catalog_cpsbasic now builds the catalog df with the correct reference to the dictionary.
However, it seems that the parsing hangs, possibly caught in one of the while conditions.
The format of the dictionary is quite different from that of other vintages. 

For example, here is the formula for finding PEEDUCA, the variable about educational attainment in the 1998-2002 dictionary.
`D PEEDUCA     2    137
T Demographics-highest level of school
  completed
     What is the highest level of school you 
     have completed or the highest degree you 
     have received? Edited Universe: 
     PEAGE&gt;=15 Valid Entries 
V         31 .Less Than 1st Grade
V         32 .1st,2nd,3rd Or 4th Grade
V         33 .5th Or 6th Grade
V         34 .7th Or 8th Grade
V         35 .9th Grade
V         36 .10th Grade
V         37 .11th Grade
V         38 .12th Grade No Diploma
V         39 .High School Grad-Diploma Or
V            .Equiv (GED)
V         40 .Some College But No Degree
V         41 .Associate
V            .Degree-Occupational/Vocationl
V         42 .Associate Deg.-Academic Program
V         43 .Bachelor's Degree(ex:ba,ab,bs)
V         44 .Master's
V            .Degree(ex:MA,MS,MEng,MEd,MSW)
V         45 .Professional School
V            .Deg(ex:MD,DDS,DVM)
V         46 .Doctorate Degree(ex:PhD,EdD)`

Notice that all rows start with a descriptor D before the variable name and only the length and beginning positionare indicated. The ending position of the variable is not included.
T is the description, and V is one of the valid entries. The same variable in the 2017-2018 dictionary is defined as follows:

`PEEDUCA		2		HIGHEST LEVEL OF SCHOOL 						137 - 138
					COMPLETED OR DEGREE RECEIVED 

					EDITED UNIVERSE:	PRPERTYP = 2 0R 3				

					VALID ENTRIES

					31	LESS THAN 1ST GRADE
					32	1ST, 2ND, 3RD OR 4TH GRADE
					33	5TH OR 6TH GRADE
					34	7TH OR 8TH GRADE
					35	9TH GRADE
					36	10TH GRADE
					37	11TH GRADE
					38	12TH GRADE NO DIPLOMA
					39	HIGH SCHOOL GRAD-DIPLOMA OR EQUIV (GED)
					40	SOME COLLEGE BUT NO DEGREE
					41	ASSOCIATE DEGREE-OCCUPATIONAL/VOCATIONAL
					42	ASSOCIATE DEGREE-ACADEMIC PROGRAM
					43	BACHELOR'S DEGREE (EX: BA, AB, BS)
					44	MASTER'S DEGREE (EX: MA, MS, MEng, MEd, MSW)
					45	PROFESSIONAL SCHOOL DEG (EX: MD, DDS, DVM)
					46	DOCTORATE DEGREE (EX: PhD, EdD)`

Thanks,
Ruben

**Comment by ajdamico** [comment]
this is helpful, thanks!  i'm not sure we need a separate script for just this period.  could you see if my edits this morning get us closer to a working data dictionary parser?  thanks for your time with this

**Comment by rubenhm** [comment]
Anthony
I downloaded 1998-01 and I think it's working fine!  
Thanks a lot for looking into this. I'm downloading the rest of the 1998-2002 vintages now.
There are some warnings about HRSAMPLE (the sample ID) when reading the file, but I think I saw those in  other years and they dont' seem to be related to the 1998 dictionary and they don't seem to affect the resulting dataframe.
Thanks!
Ruben
