### ISSUE TITLE
Unable to combine(scf_MIcombine) when unique values change across implicates.

### ISSUE THREAD

**Issue by javiertury** [ajdamico/lodown#139]
I'm trying to do a regression using `scf_MIcombine` and I would like to control for a categorical variable. I believe that due to the nature of the scf dataset, some variables that I treat as categorical are also imputed. Also I use a subset of the original scf dataset.

This gives rise to a very specific situation which causes trouble for `scf_MIcombine` and regular `MIcombine`. There could be values of that categorical variable that are unique across implicates. When any `MIcombine` function wants to merge the results it fails because the dimensions across implicates are different.

The categorical variable that I'm really using is `as.factor(year)` and the purpose is applying year fixed effects. I'm using the `SCF2013` dataset and one problematic datum is `yy1=725` on variable `x1713`. This variable is the year of origination of the first property loan.

Here is the code to replicate the problem. Suppose that `stat1` means year of loan origination and `stat2` is any numeric variable, like networth. The last `svyglm()` call uses `stat1` as year fixed effects. The code works as is. However if you use the commented definition of stat1 it will make `MIcombine` crash.

```r
## Create replicate weights
set.seed(1234)
testrw <- data.table(id=rep(1:100,999),wgt=rep(1:999,100),value=exp(rnorm(999*10)));
testrw <- dcast(testrw, id ~ wgt);
colnames(testrw) <- gsub('^([0-9]+)$','wgt\\1',colnames(testrw));

# Create fake dataset with two statistic variables, 5 implicates, 100 obs and weights
set.seed(1234)
test <- data.table(id=rep(1:100,each=5),
                   repid=rep(1:5,100),
                   wgt=exp(rnorm(100*5)),
                   stat1=rep(81:85,each=100*5/5),
                   #stat1=c(rep(81:85,each=100*5/5)[-1],75),
                   stat2=rep(41:45,each=100*5/5)
                   );

# Split fake dataset by implicates
test1 <- test[repid==1,][order(id),];
test2 <- test[repid==2,][order(id),];
test3 <- test[repid==3,][order(id),];
test4 <- test[repid==4,][order(id),];
test5 <- test[repid==5,][order(id),];

# Test, do all the implicates have the same unique values for stat1?
# This is false for the second definition of stat1
length(unique(lapply(list(test1$stat1,test2$stat1,test3$stat1,test4$stat1,test5$stat1),unique)))==1

# Create survey design for replicate weights
test_design <- svrepdesign(
  weights = ~wgt,
  repweights = testrw[,-1],
  data = imputationList(list(test1, test2, test3, test4, test5)),
  scale = 1,
  rscales = rep(1/998,999),
  mse = T,
  type = 'other',
  combined.weights = T);

# This gives warnings for both stat1 definitions, but only the second one raises an error
scf_MIcombine( with(test_design,
                    svyby(~stat2, ~as.factor(stat1),
                          svyquantile,
                          c(0,.25,.5,.75,1),
                          ci=T,
                          method='constant',
                          interval.type='quantile')))

# Only the second definition of stat1 raises an error
scf_MIcombine(with(test_design,
                   svyglm(stat2 ~ as.factor(stat1))));
```

I think that MIcombine should be more descriptive raising this error. I also wonder if there is any way to merge results using names instead of relying on dimensions. Another concern I have is that if MIcombine isn't currently merging results by name, how does it make sure that results are ordered in the same way? As of right now, MIcombine could be merging results wrongly.

Let's suppose that year 1984 is exclusive to implicate 1 but year 1985 is exclusive to implicates 2,3,4 and 5. MIcombine could potentially merge them as if they were the same year.

**Comment by ajdamico** [comment]
hi, i'm not sure there's an easy fix for the svyglm problem, sorry.  you could propose a patch to dr. lumley if you can think of a workaround.  for svyby, force levels and use `drop.empty.groups=FALSE` to make it work.  thanks


	test_design <- update( test_design , stat1 = factor( stat1 , levels = c( 75 , 81:85 ) ) )

	# This gives warnings for both stat1 definitions, but only the second one raises an error
	scf_MIcombine( with(test_design,
						svyby(~stat2, ~stat1,
							  svyquantile,
							  c(0,.25,.5,.75,1),
							  drop.empty.groups = FALSE ,
							  ci=T,
							  method='constant',
							  interval.type='quantile')))
