### ISSUE TITLE
Saving data as CSV (or other format) intead of RDS

### ISSUE THREAD

**Issue by antrologos** [ajdamico/lodown#142]
Is there a way of saving files as CSV instead of RDS? I understand RDS is very efficient and its use is recommend in various situations and for several reasons. But for a bunch of reasons an user may want to save its data directly to a simpler file (instead of openning the RDS and then "saving as...").

Congratulations for your package. Excellent job!

**Comment by ajdamico** [comment]
hi, probably won't be default but you can fork the project.. thanks
