### ISSUE TITLE
Download error with Consumer Expenditure Survey

### ISSUE THREAD

**Issue by djkpf** [ajdamico/lodown#144]
I am following the exact steps here http://asdfree.com/consumer-expenditure-survey-ces.html

When I run the following code, I receive an error:

`ces_cat <- lodown( "ces" , ces_cat )`

This is the error.

`lodown is now exiting unexpectedly.
websites that host publicly-downloadable microdata change often and sometimes those changes cause this software to break.
if the error call stack below appears to be a hiccup in your internet connection, then please verify your connectivity and retry the download.
otherwise, please open a new issue at `https://github.com/ajdamico/asdfree/issues` with the contents of this error call stack and also the output of your `sessionInfo()`.
`
This is then followed by another error:

`Error in httr_filesize(this_url, attempts, sleepsec) : 
  httr::HEAD( https://www2.census.gov/programs-surveys/cps/tables/time-series/historical-poverty-thresholds/thresh17.xls )
failed after 3 attemptshttr::HEAD( https://www2.census.gov/programs-surveys/cps/tables/time-series/historical-poverty-thresholds/thresh17.xls )
failed after 3 attempts`

I have tried to run the code with multiple internet connections.

**Comment by ajdamico** [comment]
could you submit a pull request?  thanks

**Comment by djkpf** [comment]
Hey there,

I am not actually a programmer, and am not sure what to change. I just
wanted to flag the issue.

Thanks,
Dan

**Comment by briatte** [comment]
Hi ~ It seems the issue faced by @djkpf is now gone: as of today, the `thresh17.xls` file reported in the error is not part of the catalog created by `get_catalog_ces` anymore.

I believe this issue can be closed.
