### ISSUE TITLE
Difficulty downloading 2013 PNS

### ISSUE THREAD

**Issue by klsilva** [ajdamico/lodown#145]
Hi!
I'm trying to download PNS through lodown. However, it is not possible due the warning

```
3: In readLines(this_con, encoding = sas_encoding) :
  incomplete final line found on 'C:/Users/201830~4/AppData/Local/Temp/RtmpGgdMkA/unzips/Dicionarios_e_input/input_DOMPNS2013.sas'
4: In readLines(this_con, encoding = sas_encoding) :
  incomplete final line found on 'C:/Users/201830~4/AppData/Local/Temp/RtmpGgdMkA/unzips/Dicionarios_e_input/input_PESPNS2013.sas'
```

How can I fix it?

**Comment by momenezes** [comment]
Hi @klsilva 

I also had problems loading PNS dataset; what I did was download the dataset first and use a combination of scripts from some sources to get the final survey design object.
You can find the code at:
https://gist.github.com/momenezes/50f6209802a9f5d6dba19677bbd909af
Hope this help.
Regards

**Comment by briatte** [comment]
Hi @klsilva and @momenezes 

The warnings reported by @klsilva should not stop a download. They seem to affect file conversion instead, which they should not have caused to fail either.

@klsilva, if the warnings did actually create an error, would you mind post the complete error message?

**Comment by ajdamico** [comment]
hi!  apologies for the long delay.  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining the lodown package so probably won't fix the bug you've reported.  the new asdfree does have pns data, but only for the most current year.  thanks
