### ISSUE TITLE
mics_authenticate() not working

### ISSUE THREAD

**Issue by choisy** [ajdamico/lodown#146]
At call to `mics_authenticate()` pends for ever and thus seems to fail.
Is this due to the reCAPTCHA? Any way to fix it?

**Comment by ajdamico** [comment]
hi!  apologies for the long delay.  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining the lodown package so probably won't fix the bug you've reported.  the new asdfree doesn't have mics data yet, but it's on my to-do list.  thanks
