### ISSUE TITLE
lodown unexpected stop

### ISSUE THREAD

**Issue by fandradestat** [ajdamico/lodown#148]
HI
First time trying to download such amount of data at once, i got this problems. My internet connection was working at the time this happened.
output is here
> lodown::lodown("pisa", output_dir = file.path(fernandocdir , "PISA"))
building catalog for pisa

locally downloading pisa

downloading from URL
'http://vs-web-fs-1.oecd.org/pisa/PUF_SAS_COMBINED_CMB_STU_QQQ.zip'
to file
'C:\Users\fadaniya\AppData\Local\Temp\Rtmp6pmIXh\file166c585e7002'

trying URL 'http://vs-web-fs-1.oecd.org/pisa/PUF_SAS_COMBINED_CMB_STU_QQQ.zip'
Content type 'application/x-zip-compressed' length 431313444 bytes (411.3 MB)
downloaded 411.3 MB

R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       digest_0.6.18    packrat_0.5.0    crayon_1.3.4    
 [5] R6_2.3.0         DBI_1.0.0        RSQLite_2.1.1    httr_1.4.0      
 [9] pillar_1.3.1     rlang_0.3.1      curl_3.2         rstudioapi_0.9.0
[13] blob_1.1.1       tools_3.5.2      lodown_0.1.0     bit64_0.9-7     
[17] archive_1.0.0    glue_1.3.0       bit_1.1-14       compiler_3.5.2  
[21] pkgconfig_2.0.2  memoise_1.1.0    mitools_2.3      tibble_2.0.0    

lodown is now exiting unexpectedly.
websites that host publicly-downloadable microdata change often and sometimes those changes cause this software to break.
if the error call stack below appears to be a hiccup in your internet connection, then please verify your connectivity and retry the download.
otherwise, please open a new issue at `https://github.com/ajdamico/asdfree/issues` with the contents of this error call stack and also the output of your `sessionInfo()`.

[[1]]
lodown::lodown("pisa", output_dir = file.path(fernandocdir, 
    "PISA"))

[[2]]
withCallingHandlers(catalog <- load_fun(data_name = data_name, 
    catalog, ...), error = function(e) {
    print(sessionInfo())
    if (grepl("cannot allocate vector of size", e)) 
        message(memory_note)
    else if (grepl("parameter must be specified", e)) 
        message(parameter_note)
    else if (grepl("to install", e)) 
        message(installation_note)
    else {
        message(unknown_error_note)
        print(sys.calls())
    }
})

[[3]]
load_fun(data_name = data_name, catalog, ...)

[[4]]
archive::archive_extract(tf, dir = paste0(tempdir(), "/unzips"))

[[5]]
archive_extract_(attr(archive, "path"), file)

[[6]]
stop(list(message = "archive_read_data_block(): Unsupported ZIP compression method (deflation-64-bit)", 
    call = archive_extract_(attr(archive, "path"), file), 
    cppstack = list(file = "", line = -1L, stack = "C++ stack not available on this system")))

[[7]]
(function (e) 
{
    print(sessionInfo())
    if (grepl("cannot allocate vector of size", e)) 
        message(memory_note)
    else if (grepl("parameter must be specified", e)) 
        message(parameter_note)
    else if (grepl("to install", e)) 
        message(installation_note)
    else {
        message(unknown_error_note)
        print(sys.calls())
    }
})(list(message = "archive_read_data_block(): Unsupported ZIP compression method (deflation-64-bit)", 
    call = archive_extract_(attr(archive, "path"), file), 
    cppstack = list(file = "", line = -1L, stack = "C++ stack not available on this system")))

 Error in archive_extract_(attr(archive, "path"), file) : 
  archive_read_data_block(): Unsupported ZIP compression method (deflation-64-bit)                                

6. | stop(structure(list(message = "archive_read_data_block(): Unsupported ZIP compression method (deflation-64-bit)",      call = archive_extract_(attr(archive, "path"), file), cppstack = structure(list(         file = "", line = -1L, stack = "C++ stack not available on this system"), class = "Rcpp_stack_trace")), class = c("Rcpp::exception",  "C++Error", "error", "condition"))) at RcppExports.R#21
-- | --

omitted long list of file names 

###Sesion information
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       digest_0.6.18    packrat_0.5.0    crayon_1.3.4    
 [5] R6_2.3.0         DBI_1.0.0        RSQLite_2.1.1    httr_1.4.0      
 [9] pillar_1.3.1     rlang_0.3.1      curl_3.2         rstudioapi_0.9.0
[13] blob_1.1.1       tools_3.5.2      lodown_0.1.0     bit64_0.9-7     
[17] archive_1.0.0    glue_1.3.0       bit_1.1-14       compiler_3.5.2  
[21] pkgconfig_2.0.2  memoise_1.1.0    mitools_2.3      tibble_2.0.0 
    C:\\Users\\fadaniya/PISA/2000 intstud_scie design.rds         NA

**Comment by hermelino** [comment]
I have also had this problem ... =/

**Comment by ajdamico** [comment]
hi!  apologies for the long delay.  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining the lodown package so probably won't fix the bug you've reported.  the new asdfree doesn't have pisa data yet, but it's on my to-do list.  thanks
