### ISSUE TITLE
Fix ANES (again)

### ISSUE THREAD

**Issue by briatte** [ajdamico/lodown#150]
The [ANES website](https://electionstudies.org/) is now a WordPress site, so all links to it in `lodown` are dead.

Here's code that logs into the website via an `rvest` session:

```r
if( !( 'your_email' %in% names(list(...)) ) ) stop( "`your_email` parameter must be specified.  create an account at https://www.electionstudies.org/data-center/data-registration/" )
if( !( 'your_password' %in% names(list(...)) ) ) stop( "`your_password` parameter must be specified.  create an account at https://www.electionstudies.org/data-center/data-registration/" )

your_email <- list(...)[["your_email"]]
your_password <- list(...)[["your_password"]]

# log into the anes website interactively
s <- rvest::html_session("https://electionstudies.org/wp-login.php") # session
f <- rvest::html_form(read_html(s))[[1]]
f <- rvest::set_values(f, log = your_email, pwd = your_password)
suppressMessages(rvest::submit_form(s, f)) # fill session with form

# download the `all_datasets` page to figure out what needs to be downloaded
z <- rvest::jump_to(s, "https://electionstudies.org/data-center/")
```

I have not taken the time to fix the rest of the code, but the nested download links are more easily accessible than before, it seems:

```r
nested_links <- rvest::html_nodes(z, "a.download-link")
```

For example, to get just the Stata files, I guess something like this should work:

```
rvest::html_nodes(z, xpath = "//a[@class='download-link' and contains(@href, 'dta')]") %>%
  html_attr("href")
```

Also, it should be possible to drop the code's current dependency to `purrr`.

Feel free to assign me on that one: I'm trying to find the time to (finally!) contribute to `lodown`. Also planned, WVS, Eurobarometer, and perhaps, one day, French surveys (Census, Enquête Emploi, etc., whatever can be easily downloaded).

**Comment by ajdamico** [comment]
hi François!  hope everything is great with you and apologies for the long delay.  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining the lodown package so probably won't fix the bug you've reported.  the new asdfree does have anes data, but only for the most current year.  thanks
