### ISSUE TITLE
PNAD 2001 Lodown

### ISSUE THREAD

**Issue by VillelaRaphael** [ajdamico/lodown#155]
Hi,
I am trying to download the PNAD 2001 using Lodown, but an error occurred.
I used Lodown for all the other years, from 2002 to 2015, and it worked just fine.
It seems that the problem is with 2001 files only.

I used the script below:

> pnad_cat <-get_catalog( "pnad" , output_dir = file.path( path.expand( "~" ) , "PNAD" ) )
building catalog for pnad
> pnad_cat <- subset( pnad_cat , year == 2001)
> pnad_cat <- lodown( "pnad" , pnad_cat )

Then an error occurs:

Warning: 1 parsing failure.
row # A tibble: 1 x 5 col   row col   expected actual file  expected    <int> <chr> <chr>    <chr>  <chr>   actual 1 174609 V1270 a double

There were 33 warnings (use warnings() to see them)

> warnings()
Mensagens de aviso:
1: In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 2)
2: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/00 - Brasil.doc', reason 'No such file or directory'
3: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/11 - Rondonia.doc', reason 'No such file or directory'
4: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/12 - Acre.doc', reason 'No such file or directory'
5: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/13 - Amazonas.doc', reason 'No such file or directory'
6: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/14 - Roraima.doc', reason 'No such file or directory'
7: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/15 - Para.doc', reason 'No such file or directory'
8: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/16 - Amapa.doc', reason 'No such file or directory'
9: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/17 - Tocantins.doc', reason 'No such file or directory'
10: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/21 - Maranhao.doc', reason 'No such file or directory'
11: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/22 - Piaui.doc', reason 'No such file or directory'
12: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/23 - Ceara.doc', reason 'No such file or directory'
13: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/24 - Rio Grande do Norte.doc', reason 'No such file or directory'
14: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/25 - Paraiba.doc', reason 'No such file or directory'
15: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/26 - Pernambuco.doc', reason 'No such file or directory'
16: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/27 - Alagoas.doc', reason 'No such file or directory'
17: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/28 - Sergipe.doc', reason 'No such file or directory'
18: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/29 - Bahia.doc', reason 'No such file or directory'
19: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/31 - Minas Gerais.doc', reason 'No such file or directory'
20: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/32 - Espirito Santo.doc', reason 'No such file or directory'
21: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/33 - Rio de Janeiro.doc', reason 'No such file or directory'
22: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/35 - Sao Paulo.doc', reason 'No such file or directory'
23: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/41 - Parana.doc', reason 'No such file or directory'
24: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/42 - Santa Catarina.doc', reason 'No such file or directory'
25: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/43 - Rio Grande do Sul.doc', reason 'No such file or directory'
26: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/50 - Mato Grosso do Sul.doc', reason 'No such file or directory'
27: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/51 - Mato Grosso.doc', reason 'No such file or directory'
28: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/52 - Goias.doc', reason 'No such file or directory'
29: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/CV/Unidades da Federa‡Æo/53 - Distrito Federal.doc', reason 'No such file or directory'
30: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/Metodologia/ANEXO II - Rela‡Æo de  C¢digos de Ocupa‡Æo.doc', reason 'No such file or directory'
31: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/Metodologia/ANEXO IV - Rela‡Æo de C¢digos de Atividade.doc', reason 'No such file or directory'
32: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/Metodologia/ANEXO V - Equivalˆncia em M2 das Unidades de Medida de Superf¡cie.doc', reason 'No such file or directory'
33: In file.remove(unzipped_files) :
  cannot remove file 'C:/Users/rapha/AppData/Local/Temp/RtmpaGQOjO/unzips/2001/Metodologia/ANEXO VI - Fra‡äes de Amostragem.doc', reason 'No such file or directory'

**Comment by DjalmaPessoa** [comment]
Oi Raphael,

Verifiquei que o Damico ainda não lhe respondeu.
Tentei usar a lodown para baixar a PNAD2001 e funcionou tudo bem no meu
computador.
Depois de baixar,  reproduzi alguns comandos em
http://asdfree.com/pesquisa-nacional-por-amostra-de-domicilios-pnad.html
e pareceu tudo OK. Assim, acho que o problema não é com a library lodown.
Pode ter sido algum problema com a internet. Tente novamente.
Abs,

Djalma

**Comment by ajdamico** [comment]
hi!  apologies for the long delay.  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining the lodown package so probably won't fix the bug you've reported.  the new asdfree does have pnadc data, but only for the most current year.  thanks
