### ISSUE TITLE
alternative to 7zip for mac users?

### ISSUE THREAD

**Issue by floswald** [ajdamico/lodown#157]
similarly to #156 it's not trivial to find a (command line) replacement for a 7zip unarchiver on mac os. any chance we could do some more standard compression, like zip or .tar or .gz or so?

thanks

**Comment by ajdamico** [comment]
hi!  thanks for your interest in the project and apologies for the long delay..  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining the lodown package.  appreciate it
