### ISSUE TITLE
get_catalog_nhanes() out-of-date index

### ISSUE THREAD

**Issue by HunterRatliff1** [ajdamico/lodown#160]
It looks like NHANES updated their [webpage](https://wwwn.cdc.gov/nchs/nhanes/search/DataPage.aspx), and now the function that gets the NHANES catalog is broken.

I was able to get it to work by changing the index on line 8 from `[[2]]` to `[[1]]`

**Current code:**

https://github.com/ajdamico/lodown/blob/402c30beb259d6b8daf1de113ae64b15c17b1772/R/nhanes.R#L8

**Fix that's working for me:**

` this_table <- rvest::html_table( data_html )[[1]]`

**Comment by ajdamico** [comment]
definitely submit a pull request!
