### ISSUE TITLE
fail to download lodown

### ISSUE THREAD

**Issue by leeweiching** [ajdamico/lodown#161]
this is the message i get. how to specified the lib

> install.packages("~/R/lodown-master.zip", repos = NULL, type = "win.binary")
Installing package into ‘C:/Users/Wei Ching/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)

**Comment by dwinsemius** [comment]
It's not an error message. Its geting installed into the current library location. You can change teh location with the `.libPaths` function.

**Comment by ajdamico** [comment]
hi!  thanks for your interest in the project and apologies for the long delay..  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining the lodown package.  appreciate it
