### ISSUE TITLE
Use message() rather than cat() for printing to the console 

### ISSUE THREAD

**Issue by dylanhilton** [ajdamico/lodown#162]
Some functions, particularly `get_catalog()`, can be quite verbose. Normally, you can suppress the diagnostic output of a function using `suppressMessages()`, but this method does not work when printing to the console using `cat()`.

**Comment by ajdamico** [comment]
hi!  thanks for your interest in the project and apologies for the long delay..  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining the lodown package.  appreciate it
