### ISSUE TITLE
Issue with FAERS download using lodown

### ISSUE THREAD

**Issue by AleSovera** [ajdamico/lodown#166]
```
install.packages("devtools" , repos = "http://cran.rstudio.com/")
library(devtools)
install_github("ajdamico/lodown" , dependencies = TRUE)

library(lodown)
lodown("faers" , output_dir = file.path( path.expand( "dir" ) , "FAERS"))

```

This is the code I am using. It all works for the installation portion but the actual ``lodown" command does not. I get this error:

```
trying URL 'https://www.fda.gov/Drugs/GuidanceComplianceRegulatoryInformation/Surveillance/AdverseDrugEffects/ucm082193.htm'
Content type 'text/html; charset=UTF-8' length 36002 bytes (35 KB)
downloaded 35 KB

Error in data.frame(year = ascii.years, quarter = ascii.quarter, fl = f.l,  : 
  arguments imply differing number of rows: 0, 1
```

Any advice on how to fix it?

**Comment by ajdamico** [comment]
hi!  apologies for the long delay.  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining [the lodown package](https://github.com/ajdamico/lodown) so probably won't fix the bug you've reported.  the new asdfree does have faers data, but only for the most current quarter.  thanks
