### ISSUE TITLE
Unable to downlod from DHS (dhs_authenticate error to start, later cat_fun)

### ISSUE THREAD

**Issue by danfridman** [ajdamico/lodown#167]
Hi, 

I got the error:
`dhs_authenticate: length(project.line) == 1 is not TRUE`

I think the DHS has changed their site so that the dhs_authenticate is now broken. Looking into it, the downloaded html from the DHS site is (personalized info redacted):

```
<option value="XXXXXX" >
XXXXXXProject Title----------------------...
</option>
```

Thus,  
```
y[grepl("option value", y)]
[1] "<option value=\"XXXXXX\" >" "<option value=\"XXXXXX\" >"
```

Since the project title is on a different line, 
`    project.line <- unique(y[grepl("option value", y) & 
        grepl(your_project, y, fixed = TRUE)])`
returns an empty empty vector.

So, I instead used the project number in the your_project parameter which got me past that error, but then I ran into trouble further...

```
gsub("(.*)<option value=\"([0-9]*)\">(.*)", "\\2", project.line)
[1] "<option value=\"XXXXXX\" >"

```
project.line no longer returns the project number. 

Replacing it with the actual project number in debug mode, I finally get 

```
Error in data.frame(country = this.name, year = substr(gsub("[^0-9]",  : 
  arguments imply differing number of rows: 1, 0

> traceback()
5: stop(gettextf("arguments imply differing number of rows: %s", 
       paste(unique(nrows), collapse = ", ")), domain = NA)
4: data.frame(country = this.name, year = substr(gsub("[^0-9]", 
       "", this.title), 1, 4), proj_id = project.number, Apr_Ctry_list_id = this.number, 
       output_folder = paste0(output_dir, "/", this.name, "/", this.title, 
           "/"), full_url = paste0("https://dhsprogram.com", file.url), 
       stringsAsFactors = FALSE)
3: cat_fun(data_name = data_name, output_dir = output_dir, ...)
2: get_catalog(data_name, ...)
1: lodown("dhs", output_dir = "filepath", 
       your_email = "email", your_password = "password", 
       your_project = XXXXXX)
```

Which is all the time I have today for debugging. 

I've attached the debug output (with sensitive info removed)
[Lodown debug output 20200708.txt](https://github.com/ajdamico/lodown/files/4891671/Lodown.debug.output.20200708.txt)

**Comment by ajdamico** [comment]
hi!  apologies for the long delay.  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining [the lodown package](https://github.com/ajdamico/lodown) so probably won't fix the bug you've reported.  the new asdfree doesn't have dhs data yet, but it's on my to-do list.  thanks
