### ISSUE TITLE
Unable to download hrs

### ISSUE THREAD

**Issue by psytky03** [ajdamico/lodown#168]
The hrs dataset seems not downloadable
> lodown( "hrs" , output_dir = file.path( path.expand( "~" ) , "HRS" ) , 
+         your_username = "*****" , 
+         your_password = "*****" )
building catalog for hrs

Error in if (nrow(catalog) == 0) stop("catalog must have at least one record") : 
  argument is of length zero

**Comment by ajdamico** [comment]
hi!  apologies for the long delay.  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining [the lodown package](https://github.com/ajdamico/lodown) so probably won't fix the bug you've reported.  the new asdfree doesn't have hrs data yet, but it's on my to-do list.  thanks
