### ISSUE TITLE
WVS not downloadable with lodown

### ISSUE THREAD

**Issue by MHebbat** [ajdamico/lodown#170]
When applying get_catalog or lodown function: 

wvs_cat <-  get_catalog( "wvs" , output_dir = file.path( path.expand( "~" ) , "WVS" ))

following message appears in r console:

building catalog for wvs

Fehler in data.frame(wave = this.wave, this_id = dlid, stringsAsFactors = FALSE) : 
  arguments imply differing number of rows: 1, 0

**Comment by ajdamico** [comment]
hi, this is a pretty low priority for me- you're welcome to submit a pull request if you would like this fixed?

**Comment by MHebbat** [comment]
Then the package is not relevant for me. Thanks. Also have no time to fix it..
