### ISSUE TITLE
Failure to fetch PNS data

### ISSUE THREAD

**Issue by oswaldosantos** [ajdamico/lodown#171]
When I run ` lodown("pns", output_dir = "./PNS") `, the message `building catalog for pns` appears and then 
` Error in function (type, msg, asError = TRUE)  :  Server denied you to change to the given directory `. The same code worked a few months ago.

**Comment by ajdamico** [comment]
it would be great if you could debug this and submit a pull request with the fix?

**Comment by dcpcamara** [comment]
I'm having the same problem

**Comment by ajdamico** [comment]
please submit a pull request
