### ISSUE TITLE
Problem with Area Health Resource File download

### ISSUE THREAD

**Issue by paldhous** [ajdamico/lodown#173]
Hello,

When I attempt to download with this code: lodown("ahrf", output_dir = file.path(path.expand("~"),"AHRF"))

The url constructed by the function for the download seems to be missing a slash., i.e:

trying URL 'https://data.hrsa.govDataDownload/AHRF/AHRF_2019-2020.ZIP'

Rather than:

trying URL 'https://data.hrsa.gov/DataDownload/AHRF/AHRF_2019-2020.ZIP'

**Comment by ajdamico** [comment]
please submit a pull request to fix this?
