### ISSUE TITLE
cps basic timeout

### ISSUE THREAD

**Issue by drewmcnichols** [ajdamico/lodown#174]
cpsbasic_cat <-
+   get_catalog( "cpsbasic" ,
+                output_dir = file.path( path.expand( "~" ) , "CPSBASIC" ) )
building catalog for cpsbasic

Error in open.connection(x, "rb") : 
  Failed to connect to thedataweb.rm.census.gov port 443: Operation timed out

**Comment by ajdamico** [comment]
could you submit a pull request if you're able to fix this?  thanks!

**Comment by drewmcnichols** [comment]
I’m not sure how to fix this issue. Do you have any idea what the source of the problem could be?

**Comment by drewmcnichols** [comment]
I think the problem is that the cps basic files have been moved

**Comment by ajdamico** [comment]
yes, a pull request might need to fix either the lodown_cpsbasic or
get_catalog_cpsbasic function
