### ISSUE TITLE
Issue downloading PNS data

### ISSUE THREAD

**Issue by mjaffri** [ajdamico/lodown#176]
Running >library(lodown)
+lodown( "pns" , output_dir = file.path( path.expand( "~" ) , "PNS" ) )

gives me the following error:
**Error in function (type, msg, asError = TRUE)  : 
  Server denied you to change to the given directory**

Running this with different survey data, like PNAD, works fine, though.

**Comment by ajdamico** [comment]
could you investigate `debug(lodown:::lodown_pns)` a bit and maybe submit a pull request?  thanks

**Comment by mjaffri** [comment]
If I did it right, it's telling me this:
Browse[2]> c
Error in nrow(catalog) : argument "catalog" is missing, with no default
Error in print(catalog) : argument "catalog" is missing, with no default

**Comment by ajdamico** [comment]
maybe submit a pull request with the fix?

**Comment by mjaffri** [comment]
I would, but I don't have a fix.

**Comment by mjaffri** [comment]
Does anyone have an idea for a solution?
