### ISSUE TITLE
Server denying a change of directory?

### ISSUE THREAD

**Issue by trinidadmorenosilva** [ajdamico/lodown#184]
Hi, I am trying to get the data from the PNADC but I have an issue with extracting the data from the server:
 
> lodown( "pnadc" , output_dir = file.path( path.expand( "~" ) , "PNADC"))
building catalog for pnadc
Error in function (type, msg, asError = TRUE)  : 
 Server denied you to change to the given directory

Thanks a lot

**Comment by ajdamico** [comment]
hi!  apologies for the long delay.  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining [the lodown package](https://github.com/ajdamico/lodown) so probably won't fix the bug you've reported.  the new asdfree does have pnadc data, but only for the most current year.  thanks
