### ISSUE TITLE
NSFG Data Issue for 1995 Female Response

### ISSUE THREAD

**Issue by socdoneleft** [ajdamico/lodown#185]
Hello,

The RDS file produced by lodown for the National Survey of Family Growth (NSFG) for the 1995 Female Response dataset has empty values for both the stratum variable ("col_str") and the weight variable ("post_wt"). Below I show the 1995 codebook documentation for col_str:

![image](https://user-images.githubusercontent.com/49317004/173971715-0643239b-4421-4306-8b58-e409f01cc8c4.png)

Said column is not empty in the fixed-width 1995 .DAT file -- I've highlighted cols 12347-48, which aren't empty for any line:

![image](https://user-images.githubusercontent.com/49317004/173971601-537253f0-7295-4e64-9c25-c5f4e0109fef.png)

Replication code to download 1995 RDS file:

```r
require("data.table")
require("stringr")
require("lodown")
nsfg_cat = get_catalog("nsfg", output_dir = file.path( path.expand( "~" ) , "NSFG" ) )
nsfg_dt = data.table(nsfg_cat)
nsfg_dt = nsfg_dt[str_detect(output_filename, "1995FemRespData.rds"), ]
nsfg_cat = lodown("nsfg", nsfg_dt )

vroom::problems()

nsfg1995 = readRDS(file.path( path.expand( "~" ) , "NSFG", "1995FemRespData.rds" ))
unique(nsfg1995[["col_str"]])
```

Output:

```r
nsfg catalog entry 1 of 1 stored at 'C:/Users/desk/Documents/NSFG/1995FemRespData.rds'

nsfg local download completed

Warning message:
One or more parsing issues, see `problems()` for details

> vroom::problems()
Error in vroom_materialize(x, replace = FALSE) : 
  argument "x" is missing, with no default

> nsfg1995 = readRDS(file.path( path.expand( "~" ) , "NSFG", "1995FemRespData.rds" ))
> unique(nsfg1995[["col_str"]])
[1] NA
```

Additional details:

```r
(nsfg_dt)
                                                                           full_url
1: https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Datasets/NSFG/1995FemRespData.dat
                                                                                  sas_ri
1: https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Datasets/NSFG/sas/1995FemRespSetup.sas
   beginline                                  output_filename
1:         1 C:/Users/desk/Documents/NSFG/1995FemRespData.rds
```

**Comment by ajdamico** [comment]
hi!  apologies for the long delay.  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining [the lodown package](https://github.com/ajdamico/lodown) so probably won't fix the bug you've reported.  the new asdfree does have nsfg data, but only for the most current year.  thanks
