### ISSUE TITLE
Catalog issue (CPS Basic)

### ISSUE THREAD

**Issue by kholzheu** [ajdamico/lodown#187]
>library(lodown)
>cat=get_catalog("cpsbasic", output_dir = loc)

Output:
building catalog for cpsbasic

Error in rvest::html_table(xml2::read_html(cps_ftp), fill = TRUE)[[2]] : 
  subscript out of bounds

Similarly:
> lodown( "cpsbasic" , output_dir = loc )
building catalog for cpsbasic

Error in rvest::html_table(xml2::read_html(cps_ftp), fill = TRUE)[[2]] : 
  subscript out of bounds

**Comment by ajdamico** [comment]
hi Kerstin, could you please try to send a pull request to fix this?  thanks!

**Comment by kholzheu** [comment]
Hi,  The webside "https://thedataweb.rm.census.gov/pub/cps/basic" cannot be found, so no way forward.

**Comment by ajdamico** [comment]
ha they changed the website.  a pull request would be appreciated..  thanks
