### ISSUE TITLE
There seems to be bug while downloading the hrs files

### ISSUE THREAD

**Issue by nianogo** [ajdamico/lodown#188]
https://github.com/ajdamico/lodown/blob/773cb1bf8b50c351fdcae790f1bf21ec23af3e41/R/hrs.R#L111

**Comment by ajdamico** [comment]
hi!  apologies for the long delay.  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining [the lodown package](https://github.com/ajdamico/lodown) so probably won't fix the bug you've reported.  the new asdfree doesn't have hrs data yet, but it's on my to-do list.  thanks
