### ISSUE TITLE
Add to CRAN

### ISSUE THREAD

**Issue by ParadaCarleton** [ajdamico/lodown#190]
Any reason this isn't on CRAN?

**Comment by ajdamico** [comment]
hi Carlos, i really appreciate your interest in the project!  and apologies for the long delay.  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining [the lodown package](https://github.com/ajdamico/lodown) so for sure won't submit to cran.  thanks
