### ISSUE TITLE
get_catalog('ahs') doesn't return anything

### ISSUE THREAD

**Issue by erdavis1** [ajdamico/lodown#191]
It looks like the issue might be on this [line](https://github.com/ajdamico/lodown/blob/25f82fe0d168d3d760fdadc7d35c6b6dce20de95/R/ahs.R#L22C11-L22C11) 

The website appears to have reformatted the link urls, eg:
`https://www.census.gov/programs-surveys/ahs/data.1990.List_1739896299.html`
instead of
`https://www.census.gov/programs-surveys/ahs/data.1990.html`

**Comment by ajdamico** [comment]
hi, happy to accept a pull request but i might not be able to look at this
for a while..  thanks!

**Comment by ajdamico** [comment]
hi!  apologies for the long delay.  i've made a couple of big updates to asdfree.com that hopefully make the website a bit better, but i've decided to stop maintaining [the lodown package](https://github.com/ajdamico/lodown) so probably won't fix the bug you've reported.  the new asdfree does have ahs data, but only for the most current year.  thanks
