### ISSUE TITLE
create docdir= in the catalog not a lodown_* function parameter

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/lodown#29]
it should be another column in the data frame that get_catalog_* makes.  that way, it defaults to something nicely, but users can change it the same way they can change other output names.  you will also need to add this to the dir.create() line within lodown.R so the directory gets built.  make sense?  thanks

**Comment by ajdamico** [comment]
hi, sorry for being a standardization troll.

pof does what i am describing here: https://github.com/ajdamico/lodown/blob/5120a5f379d84a37931189162d85b06b014a96d1/R/pof.R#L41-L45

you can see the `documentation` column in the catalog..

	# example where documentation files are downloaded alongside each microdata file
	head( get_catalog( "pof" , output_dir = tempdir() ) )

	


or, here's an alternative configuration if there isn't a one-to-one correspondence between data files and documentation files.  just put the documents directly into their own records in the catalog.

	ess_cat <- get_catalog( "ess" , output_dir = tempdir() )

	head( ess_cat , 20 )

**Comment by guilhermejacob** [comment]
Sure. You're the boss (:

**Comment by ajdamico** [comment]
haha nah, i am still figuring this stuff out as well

**Comment by guilhermejacob** [comment]
I think we closed this one, right? Reopen otherwise.

**Comment by ajdamico** [comment]
`sia.R` still has this mistake

**Comment by guilhermejacob** [comment]
Last commit solves it

**Comment by ajdamico** [comment]
nice, thanks
