### ISSUE TITLE
add three new lines to the ?lodown rd files for each dataset

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/lodown#30]
when you add datasets, make sure you also add lines in lodown.R and reoxygenize.  each new function pair needs one line in the first block and two lines in the second block.  i don't have this hooked up to travis so make sure you test build in rstudio..  thanks bud

**Comment by guilhermejacob** [comment]
I'll keep sia/sih out of the .Rd for now. I'll add them when I'm certain that they are working properly.
