### ISSUE TITLE
consider combining sim and sinasc into a single function

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/lodown#31]
the code in lodown_sim and lodown_sinasc looks nearly identical.  is there a good reason to keep them separate?

if they stay separate, please remove the redundant code and replace it with datasus-wide custom functions.  see lodown_icpsr and get_catalog_icpsr for an example of how to structure this.  thanks

**Comment by guilhermejacob** [comment]
I don't know. Sometimes people just want the SIM or SINASC.
If it's done separately, it's easier to combine. If done together, it's more complicated, don't you think?

**Comment by ajdamico** [comment]
hi, i think the main argument to combine them is for anyone who does want both datasets- they'd probably want them stored in a single monetdblite database.  for the case you describe, anyone who wants one but not the other, the code to separate them (below) seems straightforward to me?


	library(lodown)
	
	# download all files
	lodown( "nvss" , output_dir = "C:/My Directory/NVSS" )
	
	nvss_cat <- get_catalog( "nvss" , output_dir = "C:/My Directory/NVSS" )

	# only download natality files
	lodown( "nvss" , subset( nvss_cat , type == 'natality' ) )

	# only download mortality files
	lodown( "nvss" , subset( nvss_cat , type == 'mortality' ) )

**Comment by guilhermejacob** [comment]
Ok, got it. Will do

**Comment by ajdamico** [comment]
i think this is done?
