### ISSUE TITLE
please review censo_escolar data storage

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/lodown#42]
hi, in this commit https://github.com/ajdamico/lodown/commit/60388c4a1111334fc5474793211b8bed3151130d i removed the `db_tablename` from the catalog because it is not used.  should it be?  is the `escola` table the main table here, or should there be some other merge happening automatically?

in the same commit, i added the case_count column to the catalog using the current year's escola table.  if that's the main table for this dataset, then i think that's what we want?  what do you think?

**Comment by guilhermejacob** [comment]
I think it's fine. I think the main table is `matricula`. I don't think another merge is needed, since you merge by aggregate.
