### ISSUE TITLE
output_dir gsub should either be removed or (if there's a problem) fixed globally, not just within datasus

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/lodown#44]
https://github.com/ajdamico/lodown/commit/969f2bfe230213a0e1141fb0a4c419f49b7ba3e4

**Comment by guilhermejacob** [comment]
It's just a local issue, since the gsub strategy used here seems to be very different. I don't think this is necessary everywhere.

**Comment by ajdamico** [comment]
you've now added it to mtps and sia and sih.  what is the purpose of that line?  could you give me a minimal reproducible example or remove the line?  i don't understand why `output_dir` would not change from what the user specifies

**Comment by guilhermejacob** [comment]
for instance: 

```
# running without the gsub
library(lodown)

catalog <- get_catalog( "datasus" , output_dir = tempdir() ) 

set.seed( 123 )
smp_catalog <- catalog [ sample.int( nrow( catalog ) , size = 10 ) , ]

lodown( "datasus" , catalog = catalog )
```
Then:
```
datasus catalog entry 1 of 10 stored at 
'C:UsersgjacobAppDataLocalTempRtmp4uakJs/sim/cid9/dores/dordf81.rda'
```

**Comment by ajdamico** [comment]
could you hunt down where that mistake occurs?  it doesn't happen for me?

	lodown( "datasus" , catalog = smp_catalog )
	locally downloading datasus


	Downloading from URL

	'ftp://ftp.datasus.gov.br/dissemin/publicos/SIM/CID9/DORES/DORDF81.DBC'

	to file

	'C:\Users\anthonyd\AppData\Local\Temp\RtmpiwQJyQ\filec6c42c578aa'


	trying URL 'ftp://ftp.datasus.gov.br/dissemin/publicos/SIM/CID9/DORES/DORDF81.DBC'
	downloaded 116 KB

	datasus catalog entry 1 of 10 stored at 'C:/Users/anthonyd/AppData/Local/Temp/RtmpiwQJyQ/sim/cid9/dores/dordf81.rda'
