### ISSUE TITLE
add enquete emploi en continu

### ISSUE THREAD

**Issue by briatte** [ajdamico/lodown#45]
Please feel free to assign me to the issue if you can!

Poking @joelgombin, just in case.

**Comment by ajdamico** [comment]
hi, could you be more specific about what microdata set you'd like to add?  in other words, what's your priority number one?  thanks

**Comment by briatte** [comment]
How about

1. [Enquête Emploi en continu](https://www.insee.fr/fr/statistiques/2415511)
2. [Harmonised census](https://www.insee.fr/fr/statistiques/2414232)

?

**Comment by joelgombin** [comment]
Sounds nice. I can definitely do that.

Le jeu. 26 janv. 2017 23:58, François Briatte <notifications@github.com> a
écrit :

**Comment by ajdamico** [comment]
excellent, thanks!  how about enquete emploi en continu first?  please start with `template.R` and copy the strategies i use in the other download functions as much as you can..

**Comment by ajdamico** [comment]
migrating to https://github.com/ajdamico/asdfree/issues/202  most of the edits would still happen in lodown, though
