### ISSUE TITLE
add mtps administrative data

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/lodown#49]
i can't get to this ftp site from either a us or an ivory coast ip address  :/  if it's only administrative data, is it big enough to require monetdb?  (2 million+ records?)  thanks

**Comment by guilhermejacob** [comment]
yes. The first table has >2 million records and the others are even bigger, I assume.

**Comment by ajdamico** [comment]
thanks

**Comment by ajdamico** [comment]
migrating to https://github.com/ajdamico/asdfree/issues/195
