### ISSUE TITLE
what censo_escolar problem does this fix?

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/lodown#59]
hi, i'm confused about this commit?  i don't understand how the `gsub` would work, and don't understand the purpose of the other edits?  thanks

https://github.com/ajdamico/lodown/compare/18bc9425c6...47a15484fc

**Comment by guilhermejacob** [comment]
Sometimes, some csv copies are placed outside of the DADOS folder. The edit forces it to read this folder only.
The other forces a `gc()` after the removal of a large object. Worth it?

**Comment by guilhermejacob** [comment]
Err... nothing i said actually makes any sense. Too much coffee, too little sleep.
Revert commit, please?

![image](https://cloud.githubusercontent.com/assets/12241665/22588272/334fba40-e9ec-11e6-95b0-31803ee32682.png)

**Comment by ajdamico** [comment]
hahaha click here yo

![how to](https://cloud.githubusercontent.com/assets/216807/22588699/f98bc824-e9d4-11e6-9bce-6e2b5562d521.png)

**Comment by guilhermejacob** [comment]
Done. Thanks!
