### ISSUE TITLE
download only the 2000 and 2010 rio de janeiro extracts

### ISSUE THREAD

**Issue by DjalmaPessoa** [ajdamico/lodown#61]
this was one example in the lodown documentation for the brazilian 2000 and 2010 census. 
Is it possible, for example,  to get the data for brazilian surveys like pnad, pnadc etc just for one state?
It so happens that the stratification used by IBGE gives the same results (estimates and cvs)  working with data subset from one state and the design subset for that state, and the first could much simpler.

**Comment by ajdamico** [comment]
hi, no.  pnad and pnadc are hosted on ibge's website in nationwide files so there's no performance benefit to creating individual records

**Comment by DjalmaPessoa** [comment]
Yes, there is performance benefit !

People who work in state planning departments in Brazil just consider the
data for their state.

If we consider PNAD, for the Brazil we need to use monetdb but we don't
need  for Pernambuco. Of course for Sao Paulo it is a different thing.

**Comment by ajdamico** [comment]
hi, there's no performance benefit: you need to download and import the nationwide file no matter what.  after that, you construct a nationwide survey design the same way for everybody using the data regardless of whether they want national data or some state.  at that point, the `subset()` command to limit to the appropriate state is a single line of code.  i don't understand what steps you're envisioning that could be easier than that?

**Comment by DjalmaPessoa** [comment]
Consider the state of Roraima (small state):

1. Read directly PNAD data for Roraima in one data frame. No RAM problem
for that.
2. Define the design just for data frame of Roraima
3. You get the same results as doing for Brazil and taking the design
subset.This is true due to the stratification used for IBGE in all surveys.
In fact they are separate surveys for the sates.

The advantage is to avoid working with DBI  and when using
poststratification using the function postStratify from survey.

**Comment by ajdamico** [comment]
hi, your first bullet point is not possible?  ibge supplies the pnad data .txt files nationwide

**Comment by DjalmaPessoa** [comment]
this would be a lodown argument (data subset): to produce the subset (data
frame) just for one state in a .rda file.
The user would already get what he wants.
I've seen lots of people (most people) here in Brazil just working with
data for just one state!

**Comment by ajdamico** [comment]
the `subset()` command to limit to the appropriate state is a single line of code

**Comment by DjalmaPessoa** [comment]
For pnad we use dbi so we would have to use sql to make a filter?

**Comment by ajdamico** [comment]
no you don't.  it works exactly like any other subset

https://github.com/ajdamico/asdfree/blob/master/Pesquisa%20Nacional%20por%20Amostra%20de%20Domicilios/single-year%20-%20analysis%20examples.R#L215-L233

**Comment by DjalmaPessoa** [comment]
your example was fro subset of a design and not for subset of a table!

Ok, this was just a suggestion because most people here in Brazil start
taking the data subset just for a State. I myself don't have anything
against working with design subset.

So, I suggest you close this issue.
